import java.util.Arrays;
import java.security.SecureRandom;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.util.Base64;
import javax.crypto.spec.GCMParameterSpec;
import java.util.HexFormat;
import java.nio.charset.StandardCharsets;

/**
 * A utility class for securely handling AES-GCM encryption
 *
 * @author Jerrimiah Tomaso
 * @version 1.0
*/

public class Gibber {

    private static final SecureRandom rand = new SecureRandom();
    
    private Key key;

    
    /**
     * Creates a new instance of Gibber with a specific secret key
     *
     * @param key The {@link Key} to be used for encryption and decryption
    */

    public Gibber(Key key) {

        this.key = key;

    }

    /**
     * Encrypts a plain text string using AES-GCM-256.
     * Generates a random 12-byte IV, prepends to the ciphertext,
     * and returns the result as a Base64 encoded string.
     *
     * @param text The plain text to encrypt
     * @return A Base64 encoded string containing the IV and the ciphertext.
     * @throws Exception If the cipher cannot be initialized.
    */

    public String encrypt(String text) throws Exception {

        byte[] iv = new byte[12];
        rand.nextBytes(iv);

        SecretKeySpec keySpec = new SecretKeySpec(this.key.getEncoded(), "AES");
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, new GCMParameterSpec(128, iv));

        byte[] encryptedText = cipher.doFinal(text.getBytes(StandardCharsets.UTF_8));

        byte[] combined = new byte[iv.length + encryptedText.length];
        System.arraycopy(iv, 0, combined, 0, iv.length);
        System.arraycopy(encryptedText, 0, combined, iv.length, encryptedText.length);

        String finalText = Base64.getEncoder().encodeToString(combined);

        return finalText;

    }

    /**
     * Decrypts a Base64 encoded ciphertext string generated by this class.
     * 
     * @param text the Base64 encoded string containing the IV and ciphertext.
     * @return The original decrypted plain text string.
     * @throws Exception If decryption or authenication fails.
     * @throws IllegalArgumentException If the input is too short.
    */

    public String decrypt(String text) throws Exception {

        byte[] combined = Base64.getDecoder().decode(text);

        if (combined.length < 12) {

            throw new IllegalArgumentException("Ciphertext is too short or corrupted.");

        }

        byte[] iv = new byte[12];
        System.arraycopy(combined, 0, iv, 0, iv.length);

        byte[] cipherText = new byte[combined.length - iv.length];
        System.arraycopy(combined, iv.length, cipherText, 0, cipherText.length);

        SecretKeySpec keySpec = new SecretKeySpec(this.key.getEncoded(), "AES");
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, keySpec, new GCMParameterSpec(128, iv));

        String finalText = new String(cipher.doFinal(cipherText), StandardCharsets.UTF_8);

        return finalText;

    }
    
    /**
     * Represents a secure 256-bit AES key.
    */

    public static class Key {

        private final byte[] secureKey;

        /**
         * Generates a random key and sets it as secureKey.
        */

        public Key() {

            byte[] randomBytes = new byte[32];

            Gibber.rand.nextBytes(randomBytes);

            this.secureKey = randomBytes;

        }

        /**
         * Sets the secureKey to a existing array of bytes
         *
         * @param existingKey The existing array of bytes to use as a key.
        */

        public Key(byte[] existingKey) {
            this.secureKey = existingKey.clone();
        }

        /**
         * Sets the secureKey to a existing string
         *
         * @param existingKey The string to set the key to.
        */

        public Key(String existingKey) {
            this.secureKey = HexFormat.of().parseHex(existingKey);
        }

        /**
         * Returns the secureKey as a array of bytes.
         *
         * @return The secureKey as a array of bytes
        */

        public byte[] getEncoded() {

            return this.secureKey.clone();

        }

        /**
         * Returns the secureKey as a hexidecimal string
         *
         * @return The secureKey as a hexidecimal string
        */

        @Override
        public String toString() {
            return HexFormat.of().formatHex(this.secureKey);
        }

    }

}
